CREATE TABLE execute_log(
	id INT PRIMARY KEY,
	fqdn VARCHAR(300) NOT NULL,
	done_by VARCHAR(100) NOT NULL,
	done_at VARCHAR(100) NOT NULL,
	status BIT DEFAULT 0,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);