CREATE TABLE execute_log(
	id INT PRIMARY KEY,
	url VARCHAR(300) NOT NULL,
	done_by VARCHAR(100) NOT NULL,
	done_at VARCHAR(100) NOT NULL,
	status BIT DEFAULT 0,
	rgdt DATETIME CURRENT_TIMESTAMP,
	updt DATETIME CURRENT_TIMESTAMP
);